### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by GianniCarlo** [AppTelemetry/SwiftClient#10]
There's no license specified for the repo yet

**Comment by winsmith** [comment]
What's your recommended license? For the client, I'd like it to be as permissive as possible!

**Comment by GianniCarlo** [comment]
I believe most libraries usually go with the [MIT](https://choosealicense.com/licenses/mit/) 🤔 , anyways that site has more info on the others as well if you want to browse 👍

**Comment by winsmith** [comment]
Thanks, that was my preferred license as well! The Swift Client is now licensed under the MIT license
