### ISSUE TITLE
Allow signals in debug builds

### ISSUE THREAD

**Issue by simonnickel** [AppTelemetry/SwiftClient#14]
I would like to enable sending signals while in debug build. This would make for easier setup and integration. 

In my current analytics tool I choose different backend ids depending on debug / release builds to separate my testing data from production data. It's not a big blocker as there are ways around, but would be great to have support for this as well.

**Comment by winsmith** [comment]
You and @ddaddy seem to think alike. Have a look at #13 and see if that would help you please? I'll have a look myself when I have the time!
