### ISSUE TITLE
Signals sent in Debug Build appear as TestFlight in Viewer

### ISSUE THREAD

**Issue by ekoranek12** [AppTelemetry/SwiftClient#26]
Signals sent from a debug version of the app have their `isTestflight` value set to `true`. I think this value should be false. Ideally an `isDebug` value would also be present.

Setup configuration allowing debug signals:
```swift
let configuration = TelemetryManagerConfiguration(appID: "MY_APP_ID")
configuration.telemetryAllowDebugBuilds = true
TelemetryManager.initialize(with: configuration)
TelemetryManager.send("applicationDidFinishLaunching"
```

Signal Values:
![Screen Shot 2021-05-28 at 2 38 38 PM](https://user-images.githubusercontent.com/8239273/120034262-70164380-bfc2-11eb-94e0-312b5a1a56e1.png)

Within my personal iOS project I use this code to identify between Debug/TestFlight/AppStore for various other checks. Maybe it will be helpful for this?
```swift
public extension Bundle {
    enum DistributionSource {
        case debug, testFlight, appStore

        public var displayableTitle: String {
            switch self {
            case .debug: return "Debug"
            case .testFlight: return "TestFlight"
            case .appStore: return "App Store"
            }
        }
    }

    static var distributionSource: DistributionSource {
        #if DEBUG
        return .debug
        #else
        let isTestFlight = main.appStoreReceiptURL?.lastPathComponent == "sandboxReceipt"
        return isTestFlight ? .testFlight : .appStore
        #endif
    }
}
```

**Comment by winsmith** [comment]
Hi, thanks for reporting this! I'll investigate and get back to you!
