### ISSUE TITLE
[Mac] [Feature request] Autocomplete / dropdown when typing the signal type

### ISSUE THREAD

**Issue by GianniCarlo** [AppTelemetry/SwiftClient#9]
When creating a new Insight, and the user starts to type the `Signal Type`, it would be great if there was a dropdown or autocomplete, to avoid any typos that may arise due to misremembering the exact wording of the signal name

<img width="705" alt="Screen Shot 2020-11-10 at 17 57 22" src="https://user-images.githubusercontent.com/14112819/98743511-30697080-237e-11eb-8acb-593dc45edb05.png">

**Comment by winsmith** [comment]
Thanks, but this is a dupe :) Already on it, the lexicon is the first step for this feature

Duplicate of [TelemetryViewer#13](https://github.com/AppTelemetry/TelemetryViewer/issues/13)
